from pathlib import Path

import json
import re
import unicodedata
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

PROCESSED_DIR = Path("data/processed")
NORMALIZED_DIR = Path("data/normalized")
MANIFEST_PATH = Path("data/manifest.json")

NORMALIZATION_VERSION = 1


# ---------------------------------------------------------------------------
# Manifest helpers
# ---------------------------------------------------------------------------

def load_manifest() -> dict:
    with MANIFEST_PATH.open(
        "r",
        encoding="utf-8",
    ) as file:
        return json.load(file)


def save_manifest(manifest: dict) -> None:
    with MANIFEST_PATH.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            manifest,
            file,
            indent=2,
            ensure_ascii=False,
        )


# ---------------------------------------------------------------------------
# Encoding repair
# ---------------------------------------------------------------------------

def repair_encoding(text: str) -> tuple[str, bool]:
    """
    Repair common UTF-8 mojibake.

    Example:

        â€™ -> ’
        â€œ -> “
        â€ -> ”
        â‚¬ -> €

    Returns:
        (repaired_text, changed)
    """

    try:
        repaired = text.encode("latin1").decode("utf-8")

        if repaired != text:
            return repaired, True

    except (UnicodeEncodeError, UnicodeDecodeError):
        pass

    return text, False


# ---------------------------------------------------------------------------
# Unicode normalization
# ---------------------------------------------------------------------------

def normalize_unicode(text: str) -> tuple[str, bool]:
    """
    Normalize Unicode characters without removing meaningful content.

    NFKC is useful for documents because it normalizes compatibility
    characters while preserving semantic content.
    """

    normalized = unicodedata.normalize("NFKC", text)

    return normalized, normalized != text


# ---------------------------------------------------------------------------
# Browser / PDF artifact removal
# ---------------------------------------------------------------------------

def remove_browser_artifacts(text: str) -> tuple[str, bool]:
    """
    Remove obvious browser/PDF extraction artifacts.

    We deliberately DO NOT remove URLs globally because URLs can be
    valuable provenance information.
    """

    original = text

    # Browser timestamp such as:
    # 9/7/26, 8:17 PM
    text = re.sub(
        r"\b\d{1,2}/\d{1,2}/\d{2,4},\s*"
        r"\d{1,2}:\d{2}\s*(?:AM|PM)\b",
        "",
        text,
        flags=re.IGNORECASE,
    )

    # Standalone PDF page counters:
    # 1/3
    # 2/3
    # 3/3
    text = re.sub(
        r"(?m)^\s*\d+\s*/\s*\d+\s*$",
        "",
        text,
    )

    # Common browser URL suffixes generated by PDF printing.
    # Keep the actual URL, but remove tracking parameters where possible.
    text = re.sub(
        r"([?&])utm_[^ \n]+",
        "",
        text,
        flags=re.IGNORECASE,
    )

    return text, text != original


# ---------------------------------------------------------------------------
# Line structure normalization
# ---------------------------------------------------------------------------

def normalize_line_structure(text: str) -> tuple[str, bool]:
    """
    Normalize line endings, tabs and whitespace while preserving
    paragraph boundaries.
    """

    original = text

    # Normalize line endings.
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    # Remove null characters.
    text = text.replace("\x00", "")

    # Tabs -> spaces.
    text = text.replace("\t", " ")

    # Remove trailing whitespace.
    text = re.sub(
        r"[ \t]+$",
        "",
        text,
        flags=re.MULTILINE,
    )

    # Collapse repeated spaces, but NOT newlines.
    text = re.sub(
        r"[ ]{2,}",
        " ",
        text,
    )

    # Remove spaces immediately before/after newlines.
    text = re.sub(
        r" *\n *",
        "\n",
        text,
    )

    # Preserve at most one blank line between paragraphs.
    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text,
    )

    return text, text != original


# ---------------------------------------------------------------------------
# Hyphenation repair
# ---------------------------------------------------------------------------

def repair_hyphenated_words(text: str) -> tuple[str, bool]:
    """
    Repair words broken across lines.

    Example:

        invest-
        ment

    becomes:

        investment

    This only targets alphabetic words, reducing the chance of damaging
    meaningful numeric expressions such as 10-20 or financial identifiers.
    """

    original = text

    text = re.sub(
        r"(?<=[A-Za-z])-\n(?=[A-Za-z])",
        "",
        text,
    )

    return text, text != original


# ---------------------------------------------------------------------------
# OCR spacing repair
# ---------------------------------------------------------------------------

def normalize_ocr_spacing(text: str) -> tuple[str, bool]:
    """
    Fix common OCR spacing problems.

    Example:

        "youwith"

    is NOT blindly changed because dictionary-based correction belongs
    in a later quality-control stage.

    This stage only performs safe structural cleanup.
    """

    original = text

    # Normalize Unicode non-breaking spaces.
    text = text.replace("\u00a0", " ")

    # Normalize zero-width characters.
    text = text.replace("\u200b", "")
    text = text.replace("\u200c", "")
    text = text.replace("\u200d", "")

    return text, text != original


# ---------------------------------------------------------------------------
# Main text normalization
# ---------------------------------------------------------------------------

def normalize_text(text: str) -> tuple[str, list[str]]:
    """
    Deterministic, conservative normalization.

    The function records exactly which transformations were applied.

    No LLM is used.
    """

    changes: list[str] = []

    # 1. Encoding repair
    text, changed = repair_encoding(text)

    if changed:
        changes.append("encoding_repair")

    # 2. Unicode normalization
    text, changed = normalize_unicode(text)

    if changed:
        changes.append("unicode_normalization")

    # 3. OCR structural cleanup
    text, changed = normalize_ocr_spacing(text)

    if changed:
        changes.append("ocr_spacing_normalization")

    # 4. Browser/PDF artifact cleanup
    text, changed = remove_browser_artifacts(text)

    if changed:
        changes.append("artifact_removal")

    # 5. Hyphenated words
    text, changed = repair_hyphenated_words(text)

    if changed:
        changes.append("hyphenation_repair")

    # 6. Whitespace / line structure
    text, changed = normalize_line_structure(text)

    if changed:
        changes.append("whitespace_normalization")

    # 7. Final cleanup
    text = text.strip()

    return text, changes


# ---------------------------------------------------------------------------
# Record validation
# ---------------------------------------------------------------------------

REQUIRED_FIELDS = {
    "document_id",
    "source_file",
    "source_path",
    "page_number",
    "text",
}


def validate_record(record: dict) -> None:
    """
    Validate the minimum contract produced by extraction.
    """

    missing = REQUIRED_FIELDS - record.keys()

    if missing:
        raise ValueError(
            f"Missing required fields: {sorted(missing)}"
        )

    if not isinstance(record["page_number"], int):
        raise ValueError(
            "page_number must be an integer"
        )

    if not isinstance(record["text"], str):
        raise ValueError(
            "text must be a string"
        )


# ---------------------------------------------------------------------------
# Normalize one JSONL file
# ---------------------------------------------------------------------------

def normalize_file(
    input_path: Path,
    output_path: Path,
) -> None:
    """
    Normalize one extracted JSONL file.

    Input:
        data/processed/...

    Output:
        data/normalized/...

    Directory structure is preserved.
    """

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with input_path.open(
        "r",
        encoding="utf-8",
    ) as input_file, output_path.open(
        "w",
        encoding="utf-8",
    ) as output_file:

        for line_number, line in enumerate(
            input_file,
            start=1,
        ):

            if not line.strip():
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"Invalid JSON at line {line_number}: {exc}"
                ) from exc

            validate_record(record)

            normalized_text, changes = normalize_text(
                record["text"]
            )

            normalized_record = {
                "document_id": record["document_id"],
                "source_file": record["source_file"],
                "source_path": record["source_path"],
                "page_number": record["page_number"],
                "page_count": record.get("page_count"),
                "extraction_method": record.get(
                    "extraction_method"
                ),

                "normalization": {
                    "version": NORMALIZATION_VERSION,
                    "changes": changes,
                },

                "text": normalized_text,
            }

            output_file.write(
                json.dumps(
                    normalized_record,
                    ensure_ascii=False,
                )
                + "\n"
            )


# ---------------------------------------------------------------------------
# Process pending documents
# ---------------------------------------------------------------------------

def process_pending_documents() -> None:
    """
    Process documents whose extraction succeeded but normalization
    has not succeeded yet.

    Only the normalization section of manifest.json is modified.
    """

    manifest = load_manifest()

    processed_count = 0
    skipped_count = 0
    failed_count = 0

    for document in manifest["documents"]:

        extraction = document.get(
            "extraction",
            {},
        )

        normalization = document.get(
            "normalization",
            {},
        )

        # -------------------------------------------------------
        # Extraction must succeed first
        # -------------------------------------------------------

        if extraction.get("status") != "success":

            print(
                f"[SKIP] {document['source_path']} "
                f"(extraction not successful)"
            )

            skipped_count += 1
            continue

        # -------------------------------------------------------
        # Already normalized
        # -------------------------------------------------------

        if normalization.get("status") == "success":

            output = normalization.get("output")

            output_path = (
                NORMALIZED_DIR / Path(output)
                if output
                else None
            )

            # Important:
            # If manifest says success but output disappeared,
            # normalize it again.
            if output_path and output_path.exists():

                print(
                    f"[SKIP] {document['source_path']} "
                    f"(already normalized)"
                )

                skipped_count += 1
                continue

            print(
                f"[REPROCESS] {document['source_path']} "
                f"(manifest says success but output is missing)"
            )

        # -------------------------------------------------------
        # Locate processed JSONL
        # -------------------------------------------------------

        output_relative_path = extraction.get("output")

        if not output_relative_path:
            print(
                f"[SKIP] {document['source_path']} "
                f"(missing extraction output)"
            )

            skipped_count += 1
            continue

        input_path = (
            PROCESSED_DIR
            / Path(output_relative_path)
        )

        output_path = (
            NORMALIZED_DIR
            / Path(output_relative_path)
        )

        try:

            if not input_path.exists():
                raise FileNotFoundError(
                    f"Processed file not found: {input_path}"
                )

            print(
                f"\nNormalizing: "
                f"{document['source_path']}"
            )

            normalize_file(
                input_path,
                output_path,
            )

            processed_at = datetime.now(
                timezone.utc
            ).isoformat()

            relative_output = (
                output_path
                .relative_to(NORMALIZED_DIR)
                .as_posix()
            )

            # ---------------------------------------------------
            # Modify ONLY normalization metadata.
            # ---------------------------------------------------

            document["normalization"] = {
                "status": "success",
                "processed_at": processed_at,
                "output": relative_output,
                "error": None,
            }

            save_manifest(manifest)

            processed_count += 1

            print(
                f"[SUCCESS] {output_path}"
            )

        except Exception as exc:

            document["normalization"] = {
                "status": "failed",
                "processed_at": None,
                "output": None,
                "error": str(exc),
            }

            save_manifest(manifest)

            failed_count += 1

            print(
                f"[ERROR] "
                f"{document['source_path']}: "
                f"{exc}"
            )

    # Final manifest save.
    save_manifest(manifest)

    print("\n" + "=" * 80)
    print("NORMALIZATION SUMMARY")
    print("=" * 80)

    print(f"Processed : {processed_count}")
    print(f"Skipped   : {skipped_count}")
    print(f"Failed    : {failed_count}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    process_pending_documents()